### ISSUE TITLE
Unmarshaling error

### ISSUE THREAD

**Issue by anonysubm** [cgorenflo/fabric#2]
As part of my research I am setting up FastFabric-1.4 to run some experiments and followed the documentation in your git. I am facing a few issues and it would be great if you could guide me in the process. 

I am able to run around 500 transactions with FastFabric but beyond that unmarshaling fails on the peers. I used the same chaincode and client scripts available in this git. The exact error is shown below. Since the error only occurs when I increase the number of transactions I assume that my FastFabric setup is correct. Is this an expected error if the system cannot sustain the transaction throughput?  Do you have any suggestions for resolving this? Maybe I need to change some configurations based on my server specifications (blockBufferSize,  maxBlockCountToStore etc).

[gossip.channel] HandleMessage -> WARN 0c9 Data update contains an invalid message: Failed unmarshaling GossipMessage from envelope: unexpected EOF
github.com/hyperledger/fabric/gossip/gossip/channel.(*gossipChannel).HandleMessage
        /home/ubuntu/go/src/github.com/hyperledger/fabric/gossip/gossip/channel/channel.go:658
github.com/hyperledger/fabric/gossip/gossip.(*gossipServiceImpl).handleMessage
        /home/ubuntu/go/src/github.com/hyperledger/fabric/gossip/gossip/gossip_impl.go:378
github.com/hyperledger/fabric/gossip/gossip.(*gossipServiceImpl).acceptMessages
        /home/ubuntu/go/src/github.com/hyperledger/fabric/gossip/gossip/gossip_impl.go:332
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1581

Further, even with less than 500 transactions the orderer returns an EOF error to the clients. Despite this error the transactions are successfully committed to the blockchain, so is it fine to ignore this error?

error: [Orderer.js]: sendBroadcast - on error: "Error: 2 UNKNOWN: EOF\n    at Object.exports.createStatusError (/home/ubuntu/go/src/github.com/hyperledger/fabric/fastfabric/scripts/client/node_modules/grpc/src/common.js:91:15)\n    at ClientDuplexStream._emitStatusIfDone (/home/ubuntu/go/src/github.com/hyperledger/fabric/fastfabric/scripts/client/node_modules/grpc/src/client.js:233:26)\n    at ClientDuplexStream._receiveStatus (/home/ubuntu/go/src/github.com/hyperledger/fabric/fastfabric/scripts/client/node_modules/grpc/src/client.js:211:8)\n    at Object.onReceiveStatus (/home/ubuntu/go/src/github.com/hyperledger/fabric/fastfabric/scripts/client/node_modules/grpc/src/client_interceptors.js:1311:15)\n    at InterceptingListener._callNext (/home/ubuntu/go/src/github.com/hyperledger/fabric/fastfabric/scripts/client/node_modules/grpc/src/client_interceptors.js:568:42)\n    at InterceptingListener.onReceiveStatus (/home/ubuntu/go/src/github.com/hyperledger/fabric/fastfabric/scripts/client/node_modules/grpc/src/client_interceptors.js:618:8)\n    at /home/ubuntu/go/src/github.com/hyperledger/fabric/fastfabric/scripts/client/node_modules/grpc/src/client_interceptors.js:1127:18"

**Comment by ebinm** [comment]
Hi, I have issues with setting the network up on one local machine. Maybe you can help me?
